"""add telegram_link_token fields to users

Revision ID: f5a08726feb9
Revises: 4f4576d15065
Create Date: 2026-04-01 20:52:06.983815
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers
revision: str = 'f5a08726feb9'
down_revision: Union[str, None] = '4f4576d15065'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_link_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('telegram_link_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_link_token_expires')
    op.drop_column('users', 'telegram_link_token')
    # ### end Alembic commands ###
